# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Box settings
  config.vm.box = "generic/ubuntu2004"
  # port forwading
  config.vm.network "forwarded_port", guest: 80, host: 8080
  # shared folder
  config.vm.synced_folder "./src", "/var/www/html"
  config.vm.synced_folder "./config", "/etc/apache2/sites-available"
  # Enable provisioning with a shell script.
  config.vm.provision "shell", path: "bootstrap.sh"
end
