- name: add ssh public key for ansible
  tags: always
  authorized_key:
    user: ansible
    exclusive: yes
    key: "{{ lookup('file', '/home/becode/.ssh/ansible.pub') }}"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd