---

- hosts: all
  become: true
  tasks:

  - name: install apache, php and php support for apache
    apt:
      update_cache: yes
      name:
        - apache2
        - libapache2-mod-php
        - php
      state: latest
    when: ansible_distribution in ["Debian","Ubuntu"]
