# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "controller" do |vm1|
        vm1.vm.hostname = "controller"
        # Box settings
        vm1.vm.box = "ubuntu/focal64"
    
        # Provider settings
        vm1.vm.provider "virtualbox" do |vb|
            # customize VM name
            vb.name = "controller"
            # Customize the amount of memory on the VM:
            # vb.memory = "1024"
        end
  
        # Network settings
        vm1.vm.network "private_network", type: "dhcp"
    end

    config.vm.define "debian" do |vm2|
        vm2.vm.hostname = "debian"
        # Box settings
        vm2.vm.box = "generic/debian10"
        
        # Provider settings
        vm2.vm.provider "virtualbox" do |vb|
            # customize VM name
            vb.name = "debian-node"
            # Customize the amount of memory on the VM:
            # vb.memory = "1024"
        end
      
        # Network settings
        vm2.vm.network "private_network", type: "dhcp"
    end

    config.vm.define "ubuntu" do |vm3|
        vm3.vm.hostname = "ubuntu"
        # Box settings
        vm3.vm.box = "ubuntu/focal64"
        
        # Provider settings
        vm3.vm.provider "virtualbox" do |vb|
            # customize VM name
            vb.name = "ubuntu-node"
            # Customize the amount of memory on the VM:
            # vb.memory = "1024"
        end
        
        # Network settings
        vm3.vm.network "private_network", type: "dhcp"
    end

    config.vm.define "centos" do |vm4|
        vm4.vm.hostname = "centos"
        # Box settings
        vm4.vm.box = "generic/centos8"
        
        # Provider settings
        vm4.vm.provider "virtualbox" do |vb|
            # customize VM name
            vb.name = "centos-node"
            # Customize the amount of memory on the VM:
            # vb.memory = "1024"
        end
        
        # Network settings
        vm4.vm.network "private_network", type: "dhcp"
    end
end