- name: install apache, php and php support for apache
  apt:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_support_apache }}"
      - "{{ php_package_name }}"
    state: latest
  when: ansible_distribution in ["Debian","Ubuntu"]

- name: copy default html file for site
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
