version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins-docker
    restart: on-failure
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home: